# KallistiOS ##version##
#
# arch/xbox/hardware/Makefile
# Copyright (C) 2026 Cypress
#

# MCPX legacy block
OBJS = rtc.o

# Native kos-load syscall transport
OBJS += kosload_syscalls.o

SUBDIRS =

include $(KOS_BASE)/Makefile.prefab
