# KallistiOS ##version##
#
# arch/dreamcast/fs/Makefile
# (c)2001 Megan Potter
#

# Dreamcast-specific file systems

OBJS  = fs_iso9660.o fs_vmu.o vmufs.o
SUBDIRS =

include $(KOS_BASE)/Makefile.prefab
